// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ClusterKillJob(arg1:string):Promise<void>;

export function ClusterSubmitJob(arg1:desktop.SubmitRequest):Promise<string>;

export function ConnectNode(arg1:string,arg2:string,arg3:boolean):Promise<desktop.NodeInfo>;

export function DisconnectNode(arg1:string):Promise<void>;

export function GetAppLogCount():Promise<number>;

export function GetAppLogs(arg1:number):Promise<Array<desktop.AppLogEntry>>;

export function GetClusterCompletedJobs():Promise<Array<desktop.JobInfo>>;

export function GetClusterDashboard():Promise<desktop.DashboardInfo>;

export function GetClusterDevices():Promise<Array<desktop.ClusterDeviceInfo>>;

export function GetClusterQueuedJobs():Promise<Array<desktop.JobInfo>>;

export function GetClusterRunningJobs():Promise<Array<desktop.JobInfo>>;

export function GetClusterTopology():Promise<desktop.ClusterTopologyInfo>;

export function GetCompletedJobs():Promise<Array<desktop.JobInfo>>;

export function GetDashboard():Promise<desktop.DashboardInfo>;

export function GetDevices():Promise<Array<desktop.DeviceInfo>>;

export function GetFreeDevices():Promise<Array<desktop.DeviceInfo>>;

export function GetJobLogs(arg1:string,arg2:number):Promise<desktop.LogData>;

export function GetNodes():Promise<Array<desktop.NodeInfo>>;

export function GetQueueLength():Promise<number>;

export function GetQueuedJobs():Promise<Array<desktop.JobInfo>>;

export function GetRemoteMode():Promise<boolean>;

export function GetRunningJobs():Promise<Array<desktop.JobInfo>>;

export function GetSavedNodes():Promise<Array<desktop.SavedNodeInfo>>;

export function GetTopology():Promise<desktop.TopologyInfo>;

export function KillJob(arg1:string):Promise<void>;

export function ReconnectNode(arg1:string):Promise<desktop.NodeInfo>;

export function RemoveNode(arg1:string):Promise<void>;

export function RemoveQueuedJob(arg1:string):Promise<void>;

export function RunTerminalCommand(arg1:string,arg2:string):Promise<desktop.TerminalResult>;

export function SetNodePaths(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRemoteMode(arg1:boolean):Promise<void>;

export function SubmitJob(arg1:desktop.SubmitRequest):Promise<string>;

export function SyncFilesToNode(arg1:string,arg2:string):Promise<string>;

export function UpdateQueuedPriority(arg1:string,arg2:number):Promise<void>;
