// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDashboard() {
  return window['go']['desktop']['App']['GetDashboard']();
}

export function GetDevices() {
  return window['go']['desktop']['App']['GetDevices']();
}

export function GetFreeDevices() {
  return window['go']['desktop']['App']['GetFreeDevices']();
}

export function GetQueueLength() {
  return window['go']['desktop']['App']['GetQueueLength']();
}

export function GetRunningJobs() {
  return window['go']['desktop']['App']['GetRunningJobs']();
}

export function GetTopology() {
  return window['go']['desktop']['App']['GetTopology']();
}

export function KillJob(arg1) {
  return window['go']['desktop']['App']['KillJob'](arg1);
}

export function SubmitJob(arg1) {
  return window['go']['desktop']['App']['SubmitJob'](arg1);
}
